name: Merge Features into Develop and Create PR to Release

on:
  workflow_dispatch: # 직접 실행 버튼 추가

jobs:
  merge-features:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Git 사용자 설정
      - name: Set Git user
        run: |
          git config user.name "hello-osy"
          git config user.email "hello_osy@naver.com"
      
      # 3. Fetch remote branches
      - name: Fetch remote branches
        run: |
          git fetch origin
          
      # 4. Merge feature/graphics
      - name: Merge feature/graphics into develop
        id: graphics
        run: |
          git checkout -b develop origin/develop
          git merge origin/feature/graphics
        continue-on-error: true

      # 5. Merge feature/physics
      - name: Merge feature/physics into develop
        id: physics
        run: |
          git merge origin/feature/physics
        continue-on-error: true

      # 6. Merge feature/sfx
      - name: Merge feature/sfx into develop
        id: sfx
        run: |
          git merge origin/feature/sfx
        continue-on-error: true

      # 7. Merge feature/system
      - name: Merge feature/system into develop
        id: system
        run: |
          git merge origin/feature/system
        continue-on-error: true

      # 8. Check all merges
      - name: Check merge results
        id: check-results
        run: |
          if [[ -f result.txt ]]; then
            echo "Some merges failed. See details in result.txt."
            exit 1
          else
            echo "develop branch successfully merged with all feature branches." > result.txt
          fi

      # 9. Push develop branch (only if all merges succeeded)
      - name: Push develop
        if: steps.check-results.outcome == 'success'
        run: |
          git push origin develop

      # 10. Create PR from develop to release (only if all merges succeeded)
      - name: Create PR to release
        if: steps.check-results.outcome == 'success'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge Develop into Release"
          branch: develop
          base: release
          title: "PR: Merge Develop into Release"
          body: |
            This PR merges the latest changes from `develop` into `release`.
